site_name: rxx's notes
site_url: https://251890411.xyz
theme:
  name: material
  language: zh
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 靛蓝 · 暗色
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 靛蓝 · 亮色
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: 蓝色 · 暗色
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: 蓝色 · 亮色
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-7
        name: 护眼绿 · 暗色
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: 护眼绿 · 亮色
    - scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: 护眼暖黄 · 暗色
    - scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: 护眼暖黄 · 亮色
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow

nav:
  - 首页: index.md
  - 数学:
    - 数学/index.md
    - 数论:
      - 数学/数论/index.md
      - 第三章 数论函数:
        - 数学/数论/第三章_数论函数/index.md
        - 数论函数: 数学/数论/第三章_数论函数/数论函数.md
        - 莫比乌斯函数: 数学/数论/第三章_数论函数/莫比乌斯函数.md
        - 欧拉函数: 数学/数论/第三章_数论函数/欧拉函数.md
        - 狄利克雷卷积: 数学/数论/第三章_数论函数/狄利克雷卷积.md
        - 莫比乌斯反演: 数学/数论/第三章_数论函数/莫比乌斯反演.md
        - 积性函数: 数学/数论/第三章_数论函数/积性函数.md
  - 物理:
    - 物理/index.md
  - 编程:
    - 编程/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js

extra_css:
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.7.0/style.css
  - stylesheets/extra.css
