site_name: rxx's notes
site_url: https://251890411.xyz
theme:
  name: material
  language: zh
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换亮色模式
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换暗色模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.js
  - javascripts/katex-config.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.7.0/style.css
  - stylesheets/extra.css
